let unlockables = [
  {
    id: "orange",
    name: "Orange Fruit",
    description: "Unlocks the Orange Fruit on the map",
    requirement: { type: "points", value: 0.1 },
    price: { type: "points", value: 1 },
    effect: { property: "unlock", object: "fruit", value: true },
    unlocked: false,
    bougth: false,
    styles: {
      backgroundColor: "#ff4444",
      borderColor: "#cc0000",
      color: "#ffffff",
    },
    icon: "🍊",
  },
  {
    id: "grape",
    name: "Grape Fruit",
    description: "Unlocks the Grape Fruit on the map",
    requirement: { type: "length", value: 0 },
    price: { type: "length", value: 3 },
    effect: { property: "unlock", object: "fruit", value: true },
    unlocked: false,
    bougth: false,
    styles: {
      backgroundColor: "#a829dfff",
      borderColor: "#640f83ff",
      color: "#ffffff",
    },
    icon: "🍇",
  },
  {
    id: "banana",
    name: "Banana Fruit",
    description: "Unlocks the Banana Fruit on the map",
    requirement: { type: "points", value: 5 },
    price: { type: "points", value: 15 },
    effect: { property: "unlock", object: "fruit", value: true },
    unlocked: false,
    bougth: false,
    styles: {
      backgroundColor: "#cfec59ff",
      borderColor: "#687c24ff",
      color: "#ffffff",
    },
    icon: "🍌",
  },
  {
    id: "lime",
    name: "Lime Fruit",
    description: "Unlocks the Lime fruit on the map",
    requirement: { type: "points", value: 7 },
    price: { type: "points", value: 5 },
    effect: { property: "fruitUnlock", value: true },
    unlocked: false,
    bougth: false,
    styles: {
      backgroundColor: "#83e9adff",
      borderColor: "#2b7953ff",
      color: "#ffffff",
    },
    icon: "🍋",
  },
  {
    id: "kiwi",
    name: "Kiwi Fruit",
    description: "Unlocks the Kiwi fruit on the map",
    requirement: { type: "points", value: 1 },
    price: { type: "points", value: 100 },
    effect: { property: "unlock", object: "fruit", value: true },
    unlocked: false,
    bougth: false,
    styles: {
      backgroundColor: "#4ee78eff",
      borderColor: "#0d6038ff",
      color: "#ffffff",
    },
  },
  {
    id: "stretch",
    name: "Stretch Potion",
    description: `Increases Snake length in 1`,
    requirement: { type: "length", value: 0 },
    price: { type: "points", value: 10 },
    effect: { property: "length", value: "+1" },
    unlocked: false,
    bougth: false,
    styles: {
      backgroundColor: "#127228ff",
      borderColor: "#2b7953ff",
      color: "#ffffff",
    },
  },
];
