let unlockables = [
  {
    id: "orange",
    name: "Orange Fruit",
    description: "Unlocks the Orange Fruit on the map",
    unlocked: false,
    level: 0,
    requirement: { type: "scales", value: 0.1 },
    price: { type: "scales", value: 0.2 },
    effect: { model: "unlock", property: "fruit", value: true },
    styles: {
      backgroundColor: "#faaa60ff",
      borderColor: "#b68643ff",
      color: "#ffffff",
      backgroundImage: "url('assets/upgrades/fruits/orange.png')",
    },
    icon: "🍊",
  },
  {
    id: "grape",
    name: "Grape Fruit",
    description: "Unlocks the Grape Fruit on the map",
    unlocked: false,
    level: 0,
    // requirement: { type: "length", value: 0 },
    requirement: { type: "scales", value: 1 },
    // price: { type: "length", value: 3 },
    price: { type: "scales", value: 2 },
    effect: { model: "unlock", property: "fruit", value: true },
    styles: {
      backgroundImage: "url('assets/upgrades/fruits/grape.png')",
      backgroundColor: "#d489dd",
      borderColor: "#640f83ff",
    },
  },
  {
    id: "banana",
    name: "Banana Fruit",
    description: "Unlocks the Banana Fruit on the map",
    unlocked: false,
    level: 0,
    requirement: { type: "scales", value: 3 },
    price: { type: "scales", value: 7 },
    effect: { model: "unlock", property: "fruit", value: true },
    styles: {
      backgroundImage: "url('assets/upgrades/fruits/banana.png')",
      backgroundColor: "#e2ffa4",
      borderColor: "#687c24ff",
    },
  },
  {
    id: "lime",
    name: "Lime Fruit (LAST UNLOCKABLE SO FAR)",
    description: "Unlocks the Lime fruit on the map",
    unlocked: false,
    level: 0,
    requirement: { type: "scales", value: 5 },
    price: { type: "scales", value: 12 },
    effect: { model: "unlock", property: "fruit",value: true },
    styles: {
      backgroundImage: "url('assets/upgrades/fruits/lime.png')",
      backgroundColor: "#83e9adff",
      borderColor: "#2b7953ff",
    },
    icon: "🍋",
  },
  // {
  //   id: "kiwi",
  //   name: "Kiwi Fruit",
  //   description: "Unlocks the Kiwi fruit on the map",
  //   unlocked: false,
  //   level: 0,
  //   requirement: { type: "scales", value: 1 },
  //   price: { type: "scales", value: 100 },
  //   effect: { model: "unlock", property: "fruit", value: true },
  //   styles: {
  //     backgroundColor: "#4ee78eff",
  //     borderColor: "#0d6038ff",
  //     color: "#ffffff",
  //   },
  // },
  // {
  //   id: "stretch",
  //   name: "Stretch Ability",
  //   description: `Unlocks the ability for the snake to grow stronger`,
  //   unlocked: false,
  //   level: 0,
  //   requirement: { type: "length", value: 0 },
  //   price: { type: "scales", value: 10 },
  //   effect: { model: "unlock", property: "stretch", value: true },
  //   styles: {
  //     backgroundColor: "#127228ff",
  //     borderColor: "#2b7953ff",
  //     color: "#ffffff",
  //   },
  // },
  {
    id: "max_fruits_I",
    name: "Max Fruits!",
    description: `Increases boost capacity to increase fruits on the screen!`,
    unlocked: false,
    level: 0,
    requirement: { type: "scales", value: 1.5 },
    price: { type: "scales", value: 2.5 },
    effect: { model: "increment", property: "max_fruits", upgrades:"boosts", value: "1", series: "1" },
    styles: {
      backgroundImage:"url('assets/upgrades/boosts/max_fruits.png')",
      backgroundColor: "#87aeda",
    },
  },
  {
    id: "max_fruits_II",
    name: "Max Fruits!",
    description: `Increases boost capacity to increase fruits on the screen!`,
    unlocked: false,
    level: 0,
    requirement: { type: "scales", value: 2 },
    price: { type: "scales", value: 3 },
    effect: { model: "increment", property: "max_fruits", upgrades:"boosts", value: "1", series: "2" },
    styles: {
      backgroundImage:"url('assets/upgrades/boosts/max_fruits.png')",
      backgroundColor: "#698cb3",
    },
  },
  {
    id: "max_fruits_III",
    name: "Max Fruits!",
    description: `Increases boost capacity to increase fruits on the screen!`,
    unlocked: false,
    level: 0,
    requirement: { type: "scales", value: 5 },
    price: { type: "scales", value: 8 },
    effect: { model: "increment", property: "max_fruits", upgrades:"boosts", value: "1", series: "3" },
    styles: {
      backgroundImage:"url('assets/upgrades/boosts/max_fruits.png')",
      backgroundColor: "#4f6e91",
    },
  }
];
